### ISSUE TITLE
Almost perfect, except...

### ISSUE THREAD

**Issue by shor0814** [telnetdoogie/UDMP-ipv6#8]
Thank you so much for this, everything is working, I am able to access the internet via IPV6 as well as host IPV6 servers on my Windows box. 

Now the problem:

If I allow the iptables to update with the scripts, nothing is allowed inbound (at least no ping to the UDM or Windows IPV6 addresses), although I can still ping outbound IPV6.

If I disable the script, and go change the firewall rules in any way, everything is obviously re-written and things work again.

I have attached a dump of the 2 sets of firewall rules HE rules applied, and eth9 (after changing the firewall rules in the UI).  I have also included a screenshot of my IPV6 rules.

Something is just not quite right.

Thanks,
Shawn

[iptableseth9.txt](https://github.com/telnetdoogie/UDMP-ipv6/files/14134712/iptableseth9.txt)
[iptableshe.txt](https://github.com/telnetdoogie/UDMP-ipv6/files/14134721/iptableshe.txt)

<img width="670" alt="image" src="https://github.com/telnetdoogie/UDMP-ipv6/assets/8408954/e36d4501-c397-42b6-89cc-c2ecc82c8321">
<img width="569" alt="image" src="https://github.com/telnetdoogie/UDMP-ipv6/assets/8408954/f7276b99-2f4d-4773-ac5f-80955e5878ab">

**Comment by telnetdoogie** [comment]
which interface are you using for WAN?

Also, what's your device and UnifiOS and Network versions?

**Comment by telnetdoogie** [comment]
> If I disable the script, and go change the firewall rules in any way, everything is obviously re-written and things work again.

The reason this part works is because disabling the script and modifying the firewall rules leaves no rules at all on `he-ipv6` which means you're effectively "flapping in the wind" on the entire ipv6 network, which isn't really a good stance :)

**Comment by telnetdoogie** [comment]
I just tested firewall rules on Network 8.0.28 and UnifiOS 3.2.9 and all seems to be working properly. As a simple test, I was able to block - or enable - ping to my windows machine on one of the networks by enabling and disabling a specific rule.

Are you using the brand new EA version of Network?

You show both **LAN v6** and **Internet v6** firewall rulesets, however FYI **LAN v6** rules are not affected / touched by this. `he-ipv6` will only ever be an Internet / WAN interface. 

Below is an example "allow ping" Internet v6 rule that I used to allow ping traffic to internal hosts when testing. You might start with just a simple ping rule and then test it using [this test](https://dnschecker.org/ping-ipv6.php) to your client address on the LAN. (also ensuring that ping is allowed through your windows firewall) - a rule to ping the UDMP itself would be specified slightly differently with an `Internet v6 Local` rule. 

I _suspect_ that your firewall rule is configured incorrectly, but try this example and see if you're able to enable ping when the scripts are running.

![image](https://github.com/telnetdoogie/UDMP-ipv6/assets/17893990/91fb5c44-ea8d-46ff-b3c7-93379a6bf732)

**Comment by shor0814** [comment]
I am using eth9.  I think it is working now, just a braindead moment where
I was thinking that the WAN rules were opened and carried over to the
he-ipv6.  But no, like they should be, they are closed.  My brain skipped
past the "there are no rules defined for he-ipv6 because you didn't create
any dummy!"

The only oddity, I can't ping or access the UDMP via IPv6 from the outside
internet.  I don't know if I care too much there, what are your thoughts?

And  big thank you for making me think for a moment.

**Comment by telnetdoogie** [comment]
> The only oddity, I can't ping or access the UDMP via IPv6 from the outside internet. I don't know if I care too much there, what are your thoughts?

The rule for pinging the UDMP from the outside would be an Internet v6 rule the same as above, but with **Internet v6 Local** as the `Type` for the rule instead of **Internet v6 In**

`Internet In` = From the WAN interface to the LAN
`Internet Out` = From the LAN to the WAN interface
`Internet Local` = From the WAN interface to the UDMP itself

https://help.ui.com/hc/en-us/articles/115003173168

**Comment by shor0814** [comment]
I was missing the Internet Local.  Thank you.
